version: "3.7"
services:
    jupyter-user:
        #image: eurodatacube/jupyter-user:0.20.0
        image: eurodatacube/jupyter-user-base:t1
        environment:
        - JUPYTER_ENABLE_LAB=yes
        ports:
        - 8888:8888
        volumes:
        - .:/mnt
        - ./shared:/home/jovyan/.shared
        #command: ["bash", "-exc", "(cd /mnt && ./install_extension.sh) && bash /usr/local/bin/start-notebook.sh --watch"]
    nginx:
        image: nginx:1.17.8
        network_mode: host
        ports:
        - 8000:8000
        volumes:
        - ./dev/nginx-conf.d:/etc/nginx/conf.d
