version: "3.7"
services:
    jupyter-user:
        image: 527538141574.dkr.ecr.eu-central-1.amazonaws.com/eoxhub-jupyterlab:2023.03-02
        environment:
        - JUPYTER_ENABLE_LAB=yes
        - CATALOG_NAME=eurodatatriangle
        - CATALOG_URL=https://hub-test.eox.at/services/eoxhub-gateway/eurodatacube/notebooks
        - HOME=/tmp
        - NODE_OPTIONS=--openssl-legacy-provider # https://stackoverflow.com/questions/69394632/webpack-build-failing-with-err-ossl-evp-unsupported
        #- CATALOG_NAME=test-contest
        #- CATALOG_URL=https://test-contest-nbviewer.dev.hub.eox.at/notebooks
        ports:
        - 8888:8888
        volumes:
        - .:/mnt
        - ./shared:/home/jovyan/.shared
        user: "1000"
        command:
        - "bash"
        - "-c"
        #- "/mnt/development_install.sh && /usr/local/bin/start-notebook.sh --NotebookApp.token=''"
        - "jupyter lab --allow-root --NotebookApp.token='' --NotebookApp.ip='*'"
        #command: ["/usr/local/bin/start-notebook.sh", "--watch", "--ContentsManager.allow_hidden=True"]
    nginx:
        image: nginx:1.17.8
        network_mode: host
        volumes:
        - ./dev/nginx-conf.d:/etc/nginx/conf.d
