version: "3.7"
services:
    jupyter-user:
        image: eurodatacube/jupyter-user:0.24.5
        environment:
        - JUPYTER_ENABLE_LAB=yes
        ports:
        - 8888:8888
        volumes:
        - .:/mnt
        - ./shared:/home/jovyan/.shared
        command: ["bash", "-c", "/mnt/development_install.sh && /usr/local/bin/start-notebook.sh"]
        #command: ["/usr/local/bin/start-notebook.sh", "--watch", "--ContentsManager.allow_hidden=True"]
    nginx:
        image: nginx:1.17.8
        network_mode: host
        ports:
        - 8000:8000
        volumes:
        - ./dev/nginx-conf.d:/etc/nginx/conf.d
