version: "3.7"
services:
    jupyter-user:
        image: eurodatacube/jupyter-user:2022.02
        environment:
        - JUPYTER_ENABLE_LAB=yes
        - CATALOG_NAME=eurodatatriangle
        - CATALOG_URL=https://hub-test.eox.at/services/eoxhub-gateway/eurodatacube/notebooks
        #- CATALOG_NAME=test-contest
        #- CATALOG_URL=https://test-contest-nbviewer.dev.hub.eox.at/notebooks
        ports:
        - 8888:8888
        volumes:
        - .:/mnt
        - ./shared:/home/jovyan/.shared
        command:
        - "bash"
        - "-c"
        - "/mnt/development_install.sh && /usr/local/bin/start-notebook.sh --NotebookApp.token=''"
        #command: ["/usr/local/bin/start-notebook.sh", "--watch", "--ContentsManager.allow_hidden=True"]
    nginx:
        image: nginx:1.17.8
        network_mode: host
        volumes:
        - ./dev/nginx-conf.d:/etc/nginx/conf.d
