version: "3.7"
services:
    jupyter-user:
        image: 527538141574.dkr.ecr.eu-central-1.amazonaws.com/eurodatacube-jupyter-user:2021.12.2
        environment:
        - JUPYTER_ENABLE_LAB=yes
        #- CATALOG_NAME=eurodatacube
        #- CATALOG_URL=https://nbviewer.dev.hub.eox.at/notebooks
        - CATALOG_NAME=test-contest
        - CATALOG_URL=https://test-contest-nbviewer.dev.hub.eox.at/notebooks
        ports:
        - 8888:8888
        volumes:
        - .:/mnt
        - ./shared:/home/jovyan/.shared
        command:
        - "bash"
        - "-c"
        - "/mnt/development_install.sh && /usr/local/bin/start-notebook.sh --NotebookApp.token=''"
        #command: ["/usr/local/bin/start-notebook.sh", "--watch", "--ContentsManager.allow_hidden=True"]
    nginx:
        image: nginx:1.20.1-alpine
        network_mode: host
        ports:
        - 8000:8000
        volumes:
        - ./dev/nginx-conf.d:/etc/nginx/conf.d
